### PR TITLE
add tests, and travis and coveralls - fixes minor bugs

### PR DESCRIPTION
**Pull request by julienaubert**
I added a test-suite. I also fixed some issues where the indices where 1 off, and one bug where the page-padding would be one row of items even if page-padding was set to 0.

I also added travis (continuous integration) and coveralls (code coverage), which will run the test suite on each push and pull request. To enable travis and coveralls on your github repository, see here: http://docs.travis-ci.com/ and for coveralls: https://coveralls.io/docs

(It is already configured and fixed, so you only need to sign in to these two and login with your github account and enable this repository).

### CODE REVIEW

**Comment by thinkloop** [comment]
Awesome stuff @julienaubert! I'm working on merging this.

With regard to the bugs, let's say the viewport can show 10 items that are 10px tall each. Then the user scrolls just 5px, showing half of the first item and half the last item. In this case I keep the first visible index at 0 (since I count partial views as being viewable), while the last visible index should similarly be 10 (making 11 visible items). In fact, the majority of the time there will be 1 more item visible than the max full items, because it is unlikely to have a perfect scroll of complete items - this component ignores the perfect scroll case and just has 1 extra. Does that make sense and remove the need for some of the proposed changes?

With regard to the page-padding being 0 issue - right now the component is set to to force a minimum of 1 page padding:

`props.numPagesPadding = ko.observable(parseFloat(args.numPagesPadding) || 1)`

This is because scrolling would not be possible without at least some items being out of view and needing to be scrolled to. Given this, does the change to props.numItemsPadding still make sense?

**Comment by julienaubert** [comment]
Thanks for spotting that!

I made some changes:
- reverted numItemsPadding to always at least one span of columns, thanks!
- fixed the lastVisibleIndex so that it either adds 1 or 0. 

I see what you mean with lastVisibleIndex always has just 1 extra. I think that makes practical sense for 99% of the use-cases. The only case where it could cause trouble is if someone would use lastVisibleIndex - e.g. using it to tell user something about the last visible item. Do you see any issue with having it exactly correct as it is now in this PR?

As for the page padding, I am not sure why it should be restricted to minimum 1? It is now a public writeable observable, so one can still write 0 to it, and it works fine. Could it instead default to 1 but not restrict to 0? 

You can see this fiddle, which has pagePadding 0, works fine. (Also note how lastVisibleIndex is exactly correct).

http://jsfiddle.net/julienaubert/qWhCe/1/

PS, coveralls is up again now. Note that to get that to work in your repo, you need to sign in to travis (via your github account) and enable your repo. Same for coveralls. After that, you need to edit the README.md so that the URL's are pointing to your repo. You get these build-flags in the README.md if you do this, and makes it easier if you get PR's as travis/coveralls will post in the PR whether the PR passes the test suite.

**Comment by thinkloop** [comment]
I dropped the ball on merging this, sorry! Would it be possible to break apart the pull request into the tests/travis stuff and then a separate pull for the code changes to the actual component (I want you to get credit for it, instead of me copying it into my own commit)? 

I want to think about the code changes a little more, but want to include all the other awesomeness you did.

**Comment by julienaubert** [comment]
Hi! Feel free to pick what you need from the PR. I am not using knockout right now. I made some other  improvements as well - completely decoupled jquery/elements from the view - but I don't have the time to make a clean PR for that. If you would be interested, I could put it up in e.g. paste-bin or email it.

**Comment by thinkloop** [comment]
Thanks! I merged and fixed up all the test/coverage/travis/coveralls stuff. Thanks again, great work!

**Pull request closed without merging**
